version: '3'
services:
  nginx_load_balancer:
    image: nginx
    volumes:
      - './nginx/default.conf:/etc/nginx/nginx.conf'
      #- './nginx/index.html:/usr/share/nginx/html'
    ports:
      - '8080:80'
  app1:
    image: node-app
    environment: 
      - APPID=1111
  app2:
    image: node-app
    environment: 
      - APPID=2222